from __future__ import annotations

from .models import ParticipantType


DEFAULT_ROOM = {
    "room_name": "默认会议室",
    "goal": "通过 AI 角色与真人协作完成需求讨论、脚本编写、测试执行、结果评审和长期知识沉淀。",
}


DEFAULT_TOOLS = [
    {"tool_id": "task_breakdown", "name": "任务拆解", "description": "把需求拆成任务和验收点。", "category": "planning"},
    {"tool_id": "architecture_design", "name": "架构草案", "description": "在工作目录中生成架构草案。", "category": "design"},
    {"tool_id": "code_writer", "name": "代码草案", "description": "在工作目录中生成 Python 脚本草案。", "category": "execution"},
    {"tool_id": "embedded_c_writer", "name": "嵌入式C程序", "description": "生成适合嵌入式 Linux 场景的 C 程序骨架。", "category": "execution"},
    {"tool_id": "makefile_writer", "name": "Makefile生成", "description": "为嵌入式用户态程序生成 Makefile。", "category": "execution"},
    {"tool_id": "build_runner", "name": "本地构建", "description": "使用 gcc 或 make 构建工作目录中的程序。", "category": "execution"},
    {"tool_id": "binary_runner", "name": "程序运行", "description": "运行已构建的程序并记录输出。", "category": "execution"},
    {"tool_id": "cross_compile_probe", "name": "编译环境探测", "description": "检查 gcc、make、交叉编译器等环境。", "category": "analysis"},
    {"tool_id": "serial_log_analyzer", "name": "串口日志分析", "description": "分析日志、串口输出和报错信息。", "category": "analysis"},
    {"tool_id": "device_tree_check", "name": "设备树检查", "description": "检查设备树、BSP 和接口约束。", "category": "analysis"},
    {"tool_id": "artifact_packager", "name": "交付打包", "description": "汇总源码、二进制和说明文档。", "category": "design"},
    {"tool_id": "remote_sync", "name": "远端同步", "description": "为远端部署和同步提供占位能力。", "category": "execution"},
    {"tool_id": "remote_execute", "name": "远端执行", "description": "为远端命令执行提供占位能力。", "category": "execution"},
    {"tool_id": "artifact_reader", "name": "产物检查", "description": "读取当前会议室工作目录中的已有产物。", "category": "analysis"},
    {"tool_id": "test_runner", "name": "测试执行", "description": "尝试运行工作目录中的脚本并回传结果。", "category": "execution"},
    {"tool_id": "review_summary", "name": "评审总结", "description": "根据讨论和测试结果形成评审结论。", "category": "review"},
    {"tool_id": "question_router", "name": "相关性判断", "description": "判断当前消息是否与自己相关。", "category": "analysis"},
    {"tool_id": "run_shell_command", "name": "执行命令", "description": "在工作目录中执行安全命令并返回结果。", "category": "execution"},
    {"tool_id": "change_directory", "name": "切换目录", "description": "维护工作目录上下文。", "category": "execution"},
    {"tool_id": "list_directory", "name": "目录浏览", "description": "列出工作目录中的文件和子目录。", "category": "analysis"},
    {"tool_id": "search_text", "name": "文本搜索", "description": "在工作目录文件中搜索关键字。", "category": "analysis"},
    {"tool_id": "read_file", "name": "读取文件", "description": "读取指定产物的预览内容。", "category": "analysis"},
    {"tool_id": "write_file", "name": "写入文件", "description": "把当前上下文写入工作目录文件。", "category": "execution"},
    {"tool_id": "get_environment", "name": "环境探针", "description": "收集运行环境、Python 和当前路径信息。", "category": "analysis"},
    {"tool_id": "ssh_execute_command", "name": "SSH 执行", "description": "预留远端主机命令执行能力。", "category": "execution"},
    {"tool_id": "list_knowledge_documents", "name": "知识库列表", "description": "列出知识库中的本地文档。", "category": "analysis"},
    {"tool_id": "read_knowledge_document", "name": "知识库阅读", "description": "读取知识库中的目标文档。", "category": "analysis"},
    {"tool_id": "workspace_snapshot", "name": "工作区快照", "description": "扫描并汇总工作目录当前快照。", "category": "analysis"},
    {"tool_id": "acceptance_check", "name": "验收检查", "description": "检查关键交付物是否已经齐备。", "category": "review"},
    {"tool_id": "risk_matrix", "name": "风险矩阵", "description": "根据当前上下文做轻量风险评估。", "category": "review"},
    {"tool_id": "dependency_scan", "name": "依赖扫描", "description": "扫描实现文件中的导入依赖。", "category": "analysis"},
    {"tool_id": "document_writer", "name": "文档生成", "description": "生成交付说明或补充文档。", "category": "design"},
    {"tool_id": "test_plan", "name": "测试规划", "description": "生成主流程、异常和回归测试思路。", "category": "planning"},
    {"tool_id": "bug_report", "name": "缺陷记录", "description": "生成缺陷记录文档。", "category": "review"},
    {"tool_id": "log_summary", "name": "日志摘要", "description": "汇总当前工作区日志文件。", "category": "analysis"},
    {"tool_id": "memory_capture", "name": "记忆沉淀", "description": "把关键信息写入知识记录。", "category": "analysis"},
]


DEFAULT_LLM_PROFILES = [
    {
        "profile_id": "level1",
        "name": "qwen3-235b-a22b-thinking-2507",
        "provider": "iflow",
        "model": "qwen3-235b-a22b-thinking-2507",
        "base_url": "https://apis.iflow.cn/v1",
        "api_key": "sk-108578bf2396a9c396cc5cb1b973e834",
        "temperature": 0.0,
        "max_tokens": 131072,
        "enable_thinking": True,
        "is_default": True,
    },
    {
        "profile_id": "level2",
        "name": "qwen3-235b-a22b-instruct",
        "provider": "iflow",
        "model": "qwen3-235b-a22b-instruct",
        "base_url": "https://apis.iflow.cn/v1",
        "api_key": "sk-108578bf2396a9c396cc5cb1b973e834",
        "temperature": 0.0,
        "max_tokens": 131072,
        "enable_thinking": True,
        "is_default": False,
    },
    {
        "profile_id": "level3",
        "name": "DeepSeek-V3",
        "provider": "siliconflow",
        "model": "Pro/deepseek-ai/DeepSeek-V3.2",
        "base_url": "https://api.siliconflow.cn/v1",
        "api_key": "sk-icdjqxvbjfzptcpexcpxwksqodfufnsqwhasqwvwzouwhrwm",
        "temperature": 0.1,
        "max_tokens": 163840,
        "enable_thinking": True,
        "is_default": False,
    },
    {
        "profile_id": "level4",
        "name": "DeepSeek-V3 Stable",
        "provider": "siliconflow",
        "model": "Pro/deepseek-ai/DeepSeek-V3.2",
        "base_url": "https://api.siliconflow.cn/v1",
        "api_key": "sk-icdjqxvbjfzptcpexcpxwksqodfufnsqwhasqwvwzouwhrwm",
        "temperature": 0.0,
        "max_tokens": 163840,
        "enable_thinking": True,
        "is_default": False,
    },
    {
        "profile_id": "level5",
        "name": "Qwen3-8B",
        "provider": "siliconflow",
        "model": "Qwen/Qwen3-8B",
        "base_url": "https://api.siliconflow.cn/v1",
        "api_key": "sk-icdjqxvbjfzptcpexcpxwksqodfufnsqwhasqwvwzouwhrwm",
        "temperature": 0.1,
        "max_tokens": 131072,
        "enable_thinking": True,
        "is_default": False,
    },
]


DEFAULT_PARTICIPANTS = [
    {
        "participant_id": "p1",
        "name": "主持人",
        "role": "主持人",
        "participant_type": ParticipantType.HUMAN.value,
        "description": "组织讨论、下发嵌入式 Linux 开发任务、控制暂停和停止。",
        "enabled": True,
        "llm_profile_id": "",
        "tools": ["task_breakdown", "memory_capture"],
        "system_prompt": "你是会议主持人。你的职责是确认目标、控制节奏、在所有 AI 角色达成一致后决定继续还是结束。看到系统提示 AI 链路已收敛时，你必须明确给出继续、暂停或结束的决定。",
    },
    {
        "participant_id": "p2",
        "name": "产品专家Agent",
        "role": "产品专家Agent",
        "participant_type": ParticipantType.AI.value,
        "description": "关注嵌入式 Linux 需求边界、板卡约束、交互方式和验收口径。",
        "enabled": True,
        "llm_profile_id": "level3",
        "tools": ["question_router", "task_breakdown", "review_summary", "acceptance_check", "memory_capture"],
        "system_prompt": "你是嵌入式 Linux 产品专家。你要把需求拆成板卡目标、外设约束、输入输出形式、交付文件和验收标准。不要写空话，必须指出接下来最该由谁接力。",
    },
    {
        "participant_id": "p3",
        "name": "架构师Agent",
        "role": "架构师Agent",
        "participant_type": ParticipantType.AI.value,
        "description": "关注嵌入式 Linux 软件分层、BSP、用户态程序、构建链和验收路径。",
        "enabled": True,
        "llm_profile_id": "level1",
        "tools": ["question_router", "task_breakdown", "architecture_design", "artifact_reader", "workspace_snapshot", "risk_matrix", "device_tree_check"],
        "system_prompt": "你是嵌入式 Linux 架构师。你需要收敛模块边界、BSP 接口、驱动与用户态分工、构建方式和测试入口。每次输出都必须明确下一位接力角色。",
    },
    {
        "participant_id": "p4",
        "name": "BSP与驱动Agent",
        "role": "BSP与驱动Agent",
        "participant_type": ParticipantType.AI.value,
        "description": "关注设备树、GPIO、SPI/I2C/UART 等外设抽象和 BSP 约束。",
        "enabled": True,
        "llm_profile_id": "level4",
        "tools": ["question_router", "device_tree_check", "read_file", "search_text", "review_summary"],
        "system_prompt": "你是 BSP 与驱动 Agent。你的职责是识别板级约束、外设接口和设备树配置风险。只有在问题和内核、BSP、驱动、GPIO、串口等相关时才接力。",
    },
    {
        "participant_id": "p5",
        "name": "应用开发Agent",
        "role": "应用开发Agent",
        "participant_type": ParticipantType.AI.value,
        "description": "关注嵌入式 Linux 用户态程序实现、命令行参数、工程结构和可运行性。",
        "enabled": True,
        "llm_profile_id": "level2",
        "tools": ["question_router", "artifact_reader", "code_writer", "embedded_c_writer", "makefile_writer", "write_file", "read_file", "dependency_scan"],
        "system_prompt": "你是嵌入式 Linux 应用开发 Agent。优先输出可编译、可运行、易测试的用户态程序或辅助脚本。你必须根据测试结果继续修复，直到程序能够在 Linux 主机上实际运行。",
    },
    {
        "participant_id": "p6",
        "name": "构建发布Agent",
        "role": "构建发布Agent",
        "participant_type": ParticipantType.AI.value,
        "description": "关注 gcc/make、构建脚本、二进制产物和运行前准备。",
        "enabled": True,
        "llm_profile_id": "level4",
        "tools": ["question_router", "cross_compile_probe", "makefile_writer", "build_runner", "artifact_reader", "list_directory", "get_environment", "binary_runner"],
        "system_prompt": "你是构建发布 Agent。你负责确认编译环境、Makefile、构建命令和最终二进制是否生成。构建失败时必须明确退回开发；构建成功时必须把链路交给测试。",
    },
    {
        "participant_id": "p7",
        "name": "测试Agent",
        "role": "测试Agent",
        "participant_type": ParticipantType.AI.value,
        "description": "关注嵌入式 Linux 用户态程序的构建结果、运行结果、边界输入和验收动作。",
        "enabled": True,
        "llm_profile_id": "level5",
        "tools": ["question_router", "artifact_reader", "test_plan", "build_runner", "binary_runner", "test_runner", "acceptance_check", "bug_report", "review_summary"],
        "system_prompt": "你是测试 Agent。你必须真正运行程序、检查退出码和输出，并把结论明确写成通过、失败或待补充。只要程序还不能成功运行，就继续把任务退回给开发或构建角色。",
    },
    {
        "participant_id": "p8",
        "name": "日志分析Agent",
        "role": "日志分析Agent",
        "participant_type": ParticipantType.AI.value,
        "description": "关注串口日志、控制台输出、报错信息和失败根因。",
        "enabled": True,
        "llm_profile_id": "level5",
        "tools": ["question_router", "serial_log_analyzer", "search_text", "read_file", "log_summary", "review_summary"],
        "system_prompt": "你是日志分析 Agent。测试失败时你要解释失败现象、指出最可能的根因，并决定应该回到 BSP、开发还是构建角色。",
    },
    {
        "participant_id": "p9",
        "name": "评审Agent",
        "role": "评审Agent",
        "participant_type": ParticipantType.AI.value,
        "description": "关注程序是否真实运行成功、产物是否齐备、是否达到验收标准。",
        "enabled": True,
        "llm_profile_id": "level4",
        "tools": ["question_router", "artifact_reader", "review_summary", "acceptance_check", "risk_matrix", "artifact_packager"],
        "system_prompt": "你是评审验收 Agent。只有在测试已给出结果时才接力。你必须判断程序是否真的构建成功、运行成功、满足任务目标。如果满足，就自动形成验收通过意见并交回主持人。",
    },
    {
        "participant_id": "p10",
        "name": "文档Agent",
        "role": "文档Agent",
        "participant_type": ParticipantType.AI.value,
        "description": "关注 README、交付说明、运行命令和知识沉淀。",
        "enabled": True,
        "llm_profile_id": "level5",
        "tools": ["question_router", "document_writer", "write_file", "list_knowledge_documents", "read_knowledge_document", "artifact_packager"],
        "system_prompt": "你是文档 Agent。任务完成后，你负责生成使用说明、构建命令、运行命令和交付摘要，但不要在程序尚未跑通前抢先收口。",
    },
]


DEFAULT_ROLE_TEMPLATES = [
    {"template_id": "moderator", "name": "主持人", "role": "主持人", "participant_type": ParticipantType.HUMAN.value, "description": "负责下发任务、控制继续/暂停/停止。", "enabled": True, "llm_profile_id": "", "tools": ["task_breakdown", "memory_capture"], "system_prompt": "你是主持人，需要持续追问任务是否完成，并在评审通过后决定是否结束会议。"},
    {"template_id": "product_embedded", "name": "产品专家Agent", "role": "产品专家Agent", "participant_type": ParticipantType.AI.value, "description": "嵌入式 Linux 需求、验收与场景分析。", "enabled": True, "llm_profile_id": "level3", "tools": ["question_router", "task_breakdown", "review_summary", "acceptance_check", "memory_capture"], "system_prompt": "你要把嵌入式 Linux 任务拆成可执行目标、约束和验收标准。"},
    {"template_id": "embedded_architect", "name": "架构师Agent", "role": "架构师Agent", "participant_type": ParticipantType.AI.value, "description": "系统架构、模块边界、驱动与应用分层。", "enabled": True, "llm_profile_id": "level1", "tools": ["question_router", "task_breakdown", "architecture_design", "artifact_reader", "workspace_snapshot", "risk_matrix", "device_tree_check"], "system_prompt": "你是嵌入式 Linux 架构师，负责收敛系统分层、接口和阶段性 handoff。"},
    {"template_id": "bsp_driver", "name": "BSP与驱动Agent", "role": "BSP与驱动Agent", "participant_type": ParticipantType.AI.value, "description": "设备树、外设接口、内核约束。", "enabled": True, "llm_profile_id": "level4", "tools": ["question_router", "device_tree_check", "read_file", "search_text", "review_summary"], "system_prompt": "你关注设备树、GPIO、UART、SPI、I2C 和 BSP 约束。"},
    {"template_id": "app_dev", "name": "应用开发Agent", "role": "应用开发Agent", "participant_type": ParticipantType.AI.value, "description": "用户态程序实现与修复。", "enabled": True, "llm_profile_id": "level2", "tools": ["question_router", "artifact_reader", "code_writer", "embedded_c_writer", "makefile_writer", "write_file", "read_file", "dependency_scan"], "system_prompt": "你要产出真正可编译、可运行的用户态程序，并根据测试结论持续修复。"},
    {"template_id": "build_release", "name": "构建发布Agent", "role": "构建发布Agent", "participant_type": ParticipantType.AI.value, "description": "构建环境、编译、二进制生成。", "enabled": True, "llm_profile_id": "level4", "tools": ["question_router", "cross_compile_probe", "makefile_writer", "build_runner", "artifact_reader", "list_directory", "get_environment", "binary_runner"], "system_prompt": "你要确认构建链路跑通，构建失败就退回开发，构建成功就交给测试。"},
    {"template_id": "test_validation", "name": "测试Agent", "role": "测试Agent", "participant_type": ParticipantType.AI.value, "description": "运行测试、回归和验收前检查。", "enabled": True, "llm_profile_id": "level5", "tools": ["question_router", "artifact_reader", "test_plan", "build_runner", "binary_runner", "test_runner", "acceptance_check", "bug_report", "review_summary"], "system_prompt": "你必须真正执行程序并根据退出码和输出给出测试结论。"},
    {"template_id": "log_analyst", "name": "日志分析Agent", "role": "日志分析Agent", "participant_type": ParticipantType.AI.value, "description": "日志、串口和失败根因分析。", "enabled": True, "llm_profile_id": "level5", "tools": ["question_router", "serial_log_analyzer", "search_text", "read_file", "log_summary", "review_summary"], "system_prompt": "你只在失败或异常输出出现时接力，负责定位根因。"},
    {"template_id": "review_acceptance", "name": "评审Agent", "role": "评审Agent", "participant_type": ParticipantType.AI.value, "description": "验收程序能否通过。", "enabled": True, "llm_profile_id": "level4", "tools": ["question_router", "artifact_reader", "review_summary", "acceptance_check", "risk_matrix", "artifact_packager"], "system_prompt": "你要在程序构建成功并运行成功后再验收，不允许提前收口。"},
    {"template_id": "docs_delivery", "name": "文档Agent", "role": "文档Agent", "participant_type": ParticipantType.AI.value, "description": "交付说明、运行命令、构建说明。", "enabled": True, "llm_profile_id": "level5", "tools": ["question_router", "document_writer", "write_file", "list_knowledge_documents", "read_knowledge_document", "artifact_packager"], "system_prompt": "你要沉淀交付说明，但不要在程序未跑通前提前宣布完成。"},
    {"template_id": "security", "name": "安全审计Agent", "role": "安全审计Agent", "participant_type": ParticipantType.AI.value, "description": "命令安全和依赖风险审计。", "enabled": True, "llm_profile_id": "level4", "tools": ["question_router", "risk_matrix", "dependency_scan", "search_text", "read_file"], "system_prompt": "你在需要识别命令风险、依赖风险或输入边界时再接力。"},
]


DEFAULT_MEMORIES = [
    {
        "title": "协作原则",
        "content": "优先把目标拆成清晰任务，每轮讨论都尽量给出下一步行动和验收标准。",
        "tags": "workflow,planning,review",
        "source": "seed",
    }
]